<?php

namespace CMS\Bundle\CoreBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends EntityRepository
{
	function changeDefault() {
		return $this->_em->createQueryBuilder('l')
				         ->update('CoreBundle:Language', 'l')
				         ->set('l.default',0)
				         ->getQuery()
				         ->execute();
	}
}
