services:
    cms.media.repository.media:
        class: CMS\Bundle\MediaBundle\Entity\Repository\MediaRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['MediaBundle:Media']

    cms.media.twig.file_details.extension:
        class: CMS\Bundle\MediaBundle\Twig\Extension\FileDetailsExtension
        arguments: ['@kernel', '@cms.media.repository.media']
        public: true
        tags:
            - { name: twig.extension }

    cms.media.manager:
        class: CMS\Bundle\MediaBundle\Manager\MediaManager
        arguments: ['@kernel', '@cms.media.repository.media']

    cms.media.form.type.media_size:
        class: CMS\Bundle\MediaBundle\Form\MediaSizeType
        tags:
            - { name: form.type, alias: media_size }

    cms.media.media_option_manager:
        class: CMS\Bundle\MediaBundle\Manager\MediaOptionManager
        arguments: [@doctrine.orm.entity_manager, @cms.core.repository.option]