services:
    cms.repository.menu_taxonomy_repository:
      class: Doctrine\ORM\EntityRepository
      factory: ['@doctrine.orm.default_entity_manager', getRepository]
      arguments:
          - CMS\Bundle\MenuBundle\Entity\MenuTaxonomy

    cms.render_menu.twig_extension:
        class: CMS\Bundle\MenuBundle\Twig\RenderMenuExtension
        public: false
        arguments: ['@cms.repository.menu_taxonomy_repository', '@service_container']
        tags:
            - { name: twig.extension }