<?php

namespace CMS\Bundle\ContentBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends EntityRepository
{
    
    public function getAllContentsPublished()
    {
        return $this->_em
            ->createQueryBuilder('c, u, cat')
            ->select('c, u, cat')
            ->from('ContentBundle:Content', 'c')
            ->join('c.author', 'u')
            ->join('c.categories', 'cat')
            ->where('c.published = 1')
            ->getQuery()
            ->getResult();
        
    }
    
    public function getAllContents($cat)
    {
        $temp_children = $cat->getChildren();
        $children = array();
        foreach($temp_children as $child) {
            $children[] = $child->getId();
        }
        
        return $this->_em
            ->createQueryBuilder('co')
            ->select('co')
            ->from('ContentBundle:Content', 'co')
            ->join('co.categories', 'c')
            ->where('c.id = :cat_id')
            ->orWhere('c.id IN (:cats)')
            ->andWhere('co.published = 1')
            ->setParameter('cat_id', $cat->getId())
            ->setParameter('cats', $children)
            ->orderBy('co.created', 'DESC')
            ->getQuery()
            ->getResult();
        
    }
}
