<?php

namespace CMS\Bundle\ContentBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends EntityRepository
{

    public function findByQuery($conditions = array(), $orders = array(), $nb_element = 0, $offset = 0)
    {
        $query = $this->_em
            ->createQueryBuilder('c')
            ->select('c')
            ->from('ContentBundle:Content', 'c');
        if (!empty($conditions)) {
            $i = 0;
            foreach($conditions as $col => $value) {
                if ($i == 0) {
                    $query = $query->where('c.'.$col.' = :'.$col)
                        ->setParameter($col, $value);
                } else {
                    $query = $query->andWhere('c.'.$col.' = :'.$col)
                        ->setParameter($col, $value);
                }
                $i++;
            }
        }
        if(!empty($order)) {
            $i = 0;
            foreach($orders as $col => $sens) {
                if ($i == 0) {
                    $query = $query->orderBy('c.'.$col, $sens);
                } else {
                    $query = $query->addOrderBy('c.'.$col, $sens);
                }
                $i++;
            }
        }
        if ($offset != 0)
            $query = $query->setFirstResult($offset);
        if ($nb_element != 0)
            $query = $query->setMaxResults($nb_element);
        return $query;
    }

    public function getAllContentsNotTrashedQuery($search = '')
    {
        $query = $this->_em
            ->createQueryBuilder('c, u, cat')
            ->select('c, u, cat')
            ->from('ContentBundle:Content', 'c')
            ->join('c.author', 'u')
            ->join('c.categories', 'cat')
            ->where('c.published != 5');
        if ($search != '') {
            $query = $query->andWhere('c.title LIKE :search')
                ->orWhere('c, u, cat.title LIKE :search')
                ->setParameter('search', '%'.$search.'%');
        }

        return $query->getQuery();
    }


    public function getAllContentsTrashedQuery($search = '')
    {
        $query = $this->_em
            ->createQueryBuilder('c, u, cat')
            ->select('c, u, cat')
            ->from('ContentBundle:Content', 'c')
            ->join('c.author', 'u')
            ->join('c.categories', 'cat')
            ->where('c.published = 5')
            ->orderBy('c.id', 'DESC');
        if ($search != '') {
            $query = $query->andWhere('c.title LIKE :search')
                ->orWhere('c, u, cat.title LIKE :search')
                ->setParameter('search', '%'.$search.'%');
        }

        return $query->getQuery();
    }

    public function getAllContentsPublished()
    {
        return $this->_em
            ->createQueryBuilder('c, u, cat')
            ->select('c, u, cat')
            ->from('ContentBundle:Content', 'c')
            ->join('c.author', 'u')
            ->join('c.categories', 'cat')
            ->where('c.published = 1')
            ->getQuery()
            ->getResult();

    }

    public function getAllContents($cat)
    {
        $temp_children = $cat->getChildren();
        $children = array();
        foreach ($temp_children as $child) {
            $children[] = $child->getId();
        }

        return $this->_em
            ->createQueryBuilder('co')
            ->select('co')
            ->from('ContentBundle:Content', 'co')
            ->join('co.categories', 'c')
            ->where('c.id = :cat_id')
            ->orWhere('c.id IN (:cats)')
            ->andWhere('co.published = 1')
            ->setParameter('cat_id', $cat->getId())
            ->setParameter('cats', $children)
            ->orderBy('co.created', 'DESC')
            ->getQuery()
            ->getResult();

    }

    public function getCountByTaxonomy()
    {
        return $this->_em
            ->createQueryBuilder('c')
            ->select('COUNT(c) as total, t.title')
            ->from('ContentBundle:Content', 'c')
            ->leftJoin('c.taxonomy', 't')
            ->groupBy('c.taxonomy')
            ->having('total > 0')
            ->getQuery()
            ->getResult();
    }

    public function getCountByMonth()
    {
        return $this->_em
            ->createQueryBuilder('c')
            ->select('COUNT(c) as total, YEAR(c.created) as year_created, MONTH(c.created) as month_created')
            ->from('ContentBundle:Content', 'c')
            ->groupBy('year_created, month_created')
            ->getQuery()
            ->getResult();
    }


    public function getValuesByMonth($taxonomy, $title_field)
    {
        return $this->_em
            ->createQueryBuilder('c')
            ->select('fv.value as total, YEAR(c.created) as year_created, MONTH(c.created) as month_created')
            ->from('ContentBundle:Content', 'c')
            ->leftJoin('c.taxonomy', 't', 't.id = '.$taxonomy->getId())
            ->leftJoin('c.fieldvalues', 'fv')
            ->leftJoin('fv.field', 'f')
            ->where('f.title = :title_field')
            ->setParameter('title_field', $title_field)
            ->orderBy('c.created', 'ASC')
            ->getQuery()
            ->getResult();
    }


    public function getRelatedPosts($id_post, $limit)
    {
        $categories = $this->_em
            ->createQueryBuilder()
            ->select('cat.id')
            ->from('ContentBundle:Category', 'cat')
            ->leftJoin('cat.contents', 'c')
            ->where('c.id = :id')
            ->setParameter('id', $id_post)
            ->getQuery()
            ->getScalarResult();

        return $this->_em
            ->createQueryBuilder()
            ->select('c')
            ->from('ContentBundle:Content', 'c')
            ->leftJoin('c.categories', 'cat')
            ->where('cat.id IN (:ids)')
            ->setParameter('ids', $categories)
            ->andWhere('c.id != :id')
            ->setParameter('id', $id_post)
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }


    public function search($query)
    {
        return $this->_em
            ->createQueryBuilder()
            ->select('c')
            ->from('ContentBundle:Content', 'c')
            ->where('c.title LIKE :query')
            ->orWhere('c.description LIKE :query')
            ->setParameter('query', '%'.$query.'%')
            ->getQuery()
            ->getResult();
    }

    public function updateStatus($ids, $status)
    {
        return $this->_em
            ->createQueryBuilder()
            ->update('ContentBundle:Content', 'c')
            ->where('c.id IN (:ids)')
            ->setParameter('ids', $ids)
            ->set('c.published', $status)
            ->getQuery()
            ->execute();
    }

    public function deleteTotally(array $ids)
    {
        return $this->_em
            ->createQueryBuilder()
            ->delete('ContentBundle:Content', 'c')
            ->where('c.id IN (:ids)')
            ->setParameter('ids', $ids)
            ->getQuery()
            ->execute();
    }

    public function getContentsBy(array $params)
    {
        $query = $this->_em
            ->createQueryBuilder()
            ->select('c')
            ->from('ContentBundle:Content', 'c')
            ->where('c.published = 1');
        foreach($params as $key => $value) {
            switch($key) {
                case 'author':
                    if (strpos($value, ',') === false) {
                        $query = $query->leftJoin('c.author', 'u')
                            ->andWhere('u.id = :author_id')
                            ->setParameter('author_id', $value);
                    } else {
                        $query = $query->leftJoin('c.author', 'u')
                            ->andWhere('u.id IN (:author_id)')
                            ->setParameter('author_id', explode(',', $value));
                    }
                    break;
                case 'author_name':
                    $query = $query->leftJoin('c.author', 'u')
                        ->andWhere('u.display_name = :author_name')
                        ->setParameter('author_name', $value);
                    break;
                case 'cat':
                    if (strpos($value, ',') === false) {
                        $query = $query->leftJoin('c.categories', 'cat')
                            ->andWhere('cat.id = :cat_id')
                            ->setParameter('cat_id', $value);
                    } else {
                        $query = $query->leftJoin('c.categories', 'cat')
                            ->andWhere('cat.id IN (:cat_id)')
                            ->setParameter('cat_id', explode(',', $value));
                    }
                    break;
                case 'category_name':
                    $query = $query->leftJoin('c.categories', 'cat')
                        ->andWhere('cat.url = :cat_url')
                        ->setParameter('cat_url', $value);
                    break;
                case 'post_type':
                    $query = $query->leftJoin('c.taxonomy', 'tax')
                        ->andWhere('tax.alias = :tax_alias')
                        ->setParameter('alias', $value);
                    break;
                case 'tax_query':
                    $query = $query->leftJoin('c.taxonomy', 'tax');
                    foreach($value as $key_tax => $value_tax) {
                        switch($key_tax) {
                            case 'taxonomy':
                                $query = $query->andWhere('tax.alias = :taxquery_alias')
                                    ->setParameter('taxquery_alias', $value_tax);
                                break;
                            case 'field':
                                $query = $query->leftJoin('tax.fields', 'field')
                                    ->andWhere('field.name = :field_name')
                                    ->setParameter('field_name', $value_tax);
                                break;
                            case 'terms':
                                $query = $query->leftJoin('c.fieldvalues', 'fieldvalues')
                                    ->andWhere('fieldvalues.value = :field_value')
                                    ->setParameter('field_value', $value_tax);
                                break;
                        }
                    }
                    break;
                case 'p':
                    $query = $query->andWhere('c.id = :id_post')
                        ->setParameter('id_post', $value);
                    break;
                case 'posts_per_page':
                    $query = $query->setMaxResults($value);
                    break;
                case 'offset':
                    $query = $query->setFirstResult($value);
                    break;
                case 'orderby':
                    $order = 'ASC';
                    if (isset($params['order'])) {
                        $order = $params['order'];
                    }
                    $query = $query->orderBy('c.'.$value, $order);
                case 'title':
                    $query = $query->andWhere('c.title = :title')
                        ->setParameter('title', $value);
                    break;
                case 's':
                    $query = $query->andWhere('c.title LIKE %:search%')
                        ->orWhere('c.description LIKE %:search%')
                        ->setParameter('search', $value);
                    break;
            }
        }
        return $query->getQuery()->getResult();
    }
}
