<?php

namespace CMS\Bundle\ContentBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldRepository extends EntityRepository
{

	public function findByTaxonomyIndexed($content_taxonomy)
	{
		return $this->_em
					->createQueryBuilder('f')
					->select('f')
					->from('ContentBundle:Field', 'f', 'f.name')
					->leftJoin('f.contentTaxonomy', 'ct')
					->where('ct.id = :id')
					->setParameter('id', $content_taxonomy->getId())
					->getQuery()
					->getResult();
	}
}
