<?php

namespace CMS\Bundle\ContentBundle\Entity\Repository;

use CMS\Bundle\ContentBundle\Entity\Content;

/**
 * FieldValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldValueRepository extends \Doctrine\ORM\EntityRepository
{

	public function findFielvalueByContent(Content $content)
	{
		return $this->_em
			        ->createQueryBuilder('fv')
			        ->select('fv, f, c')
			        ->from('ContentBundle:FieldValue', 'fv')
			        ->join('fv.content', 'c')
			        ->join('fv.field', 'f')
			        ->where('fv.content = :content')
			        ->setParameter('content', $content)
			        ->getQuery()
			        ->getResult();
	}
}
