<?php

namespace CMS\Bundle\ContentBundle\Entity\Repository;

use CMS\Bundle\ContentBundle\Entity\Content;

/**
 * MetaValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetaValueRepository extends \Doctrine\ORM\EntityRepository
{

    public function findMetavalueByContent(Content $content)
    {
        return $this->_em
            ->createQueryBuilder()
            ->select('mv, m, c')
            ->from('ContentBundle:MetaValue', 'mv')
            ->join('mv.content', 'c')
            ->join('mv.meta', 'm')
            ->where('mv.content = :content')
            ->setParameter('content', $content)
            ->orderBy('m.order', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
