<?php

namespace CMS\Bundle\ContentBundle\Entity\Repository;

/**
 * MetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetaRepository extends \Doctrine\ORM\EntityRepository
{
}
