CMS\Bundle\CoreBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        user_login:
            expose: true
        user_email:
            expose: true
        user_nicename:
            expose: true