imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine_extensions.yml }

parameters:
    locale: fr
    db.table_prefix: cms_
    sass.bin: '/usr/local/bin/sass'
    compass.bin: '/usr/local/bin/compass'
    ruby.bin: '/usr/bin/ruby'
    web_path: %kernel.root_dir%/../web

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']

        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    assets:
        packages:
            templates:
                base_path: "/templates"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes: ['::form.html.twig']
    globals:
        web_path: %web_path%
    paths:
        "%kernel.root_dir%/../templates": cms

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ CoreBundle ]
    ruby: %ruby.bin%
    filters:
        cssrewrite: ~
        sass:
            bin: %sass.bin%
        compass:
            bin: %compass.bin%
        jsqueeze: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        entity_listener_resolver: cms.content.doctrine.entity_listener_resolver

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

core:
    theme:
        dir: "%kernel.root_dir%/../templates"


sensio_framework_extra:
    view:   { annotations: false }
    router: { annotations: true }

fos_js_routing:
     routes_to_expose: [ (.*) ]

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json
    serializer:
        serialize_null: true

liip_imagine:
    filter_sets:
        thumb_list:
            quality: 90
            filters:
                thumbnail: {size: [286, 215], mode: outbound }