imports:
    - { resource: config.yml }

parameters:
    locale: fr
    sass.bin: '/usr/local/bin/sass'
    compass.bin: '/usr/local/bin/compass'
    ruby.bin: '/usr/bin/ruby'
    web_path: '%kernel.root_dir%/../web'


framework:
    assets:
        base_urls: ['https://choupdoune.fr/']
        packages:
            templates:
                base_path: "/templates"

# Twig Configuration
twig:
    exception_controller: cms.core.exception_controller:showAction


monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            channels: [!event]
            max_files: 10
        nested:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
        console:
            type:  console