widget:
    resource: "@WidgetBundle/Controller/"
    type:     annotation
    prefix:   /

menu:
    resource: "@MenuBundle/Controller/"
    type:     annotation
    prefix:   /

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /

dashboard:
    resource: "@DashboardBundle/Controller/"
    type:     annotation
    prefix:   /

content:
    resource: "@ContentBundle/Controller/"
    type:     annotation
    prefix:   /

contact:
    resource: "@ContactBundle/Controller/"
    type:     annotation
    prefix:   /

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

login_check:
    path: /admin/login_check

logout:
    path: /admin/logout