content_meta:
    resource: "@ContentBundle/Controller/MetaController.php"
    type:     annotation

core_widget:
    resource: "@CoreBundle/Controller/WidgetController.php"
    type:     annotation

menu:
    resource: "@MenuBundle/Controller/"
    type:     annotation
    prefix:   /

media:
    resource: "@MediaBundle/Controller/"
    type:     annotation
    prefix:   /admin/media

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /



rest_api:
    resource: "@RestAPIBundle/Controller/"
    type:     annotation
    prefix:   /

contents:
    type:   rest
    resource: CMS\Bundle\RestAPIBundle\Controller\ContentsController
    prefix: /rest

dashboard:
    resource: "@DashboardBundle/Controller/"
    type:     annotation
    prefix:   /

content:
    resource: "@ContentBundle/Controller/"
    type:     annotation
    prefix:   /

contact:
    resource: "@ContactBundle/Controller/"
    type:     annotation
    prefix:   /



login_check:
    path: /admin/login_check

logout:
    path: /admin/logout

fos_js_routing:
     resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

