# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        CMS\Bundle\CoreBundle\Entity\User: sha1

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        main:
            entity: { class: CoreBundle:User }
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/admin/login$
            security: false

        secured_area:
            pattern:    ^/admin/
            form_login:
                check_path: login_check
                login_path: admin_login
                always_use_default_target_path: false
                default_target_path:            /admin/dashboard
                use_referer: true
            logout:
                path:   logout
                target: admin_login
            anonymous: ~

            #http_basic:
            #    realm: "Secured Demo Area"


    access_control:
        - { path: ^/admin/install, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/forgot, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/change_password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }