parameters:

services:
    cms.content.content_manager:
        class: CMS\Bundle\ContentBundle\Manager\ContentManager
        arguments: [ @doctrine.orm.entity_manager ]

    cms.content.form.type.map:
            class: CMS\Bundle\ContentBundle\Form\Type\MapType
            tags:
                - { name: form.type, alias: map }

    cms.content.fields:
        class: CMS\Bundle\ContentBundle\Classes\Fields
        calls:
            - [ setTemplating, [ @twig ] ]

    cms.content.map_field:
            class: CMS\Bundle\ContentBundle\Entity\Fields\MapField
            calls:
                - [ setTemplating, [ @twig ] ]

    cms.content.doctrine.entity_listener_resolver:
        class: CMS\Bundle\ContentBundle\Doctrine\EntityListenerResolver
        arguments: [ "@service_container" ]
        

    cms.content.entity_listener.content:
        class: CMS\Bundle\ContentBundle\Listener\ContentListener
        arguments: [ "@service_container" ]
        tags:
            -  { name: doctrine.entity_listener }