parameters:

services:
    cms.content.content_manager:
        class: CMS\Bundle\ContentBundle\Manager\ContentManager
        arguments: [ "@doctrine.orm.entity_manager" ]

    cms.content.form.type.map:
        class: CMS\Bundle\ContentBundle\Form\Type\MapType
        tags:
            - { name: form.type, alias: map }

    cms.content.form.type.weather:
        class: CMS\Bundle\ContentBundle\Form\Type\WeatherType
        tags:
            - { name: form.type, alias: weather }

    cms.content.form.type.spotify:
        class: CMS\Bundle\ContentBundle\Form\Type\SpotifyType
        tags:
            - { name: form.type, alias: spotify }

    cms.content.form.type.deezer:
        class: CMS\Bundle\ContentBundle\Form\Type\DeezerType
        tags:
            - { name: form.type, alias: deezer }

    cms.content.form.type.gallery:
        class: CMS\Bundle\ContentBundle\Form\Type\GalleryType
        tags:
            - { name: form.type, alias: gallery }

    cms.content.form.data_tranformer.gallery:
        class: CMS\Bundle\ContentBundle\Form\DataTransformer\MediaToIdTransformer
        arguments: ["@doctrine.orm.entity_manager"]

    cms.content.fields:
        class: CMS\Bundle\ContentBundle\Classes\Fields
        calls:
            - [ setTemplating, [ '@templating' ] ]

    cms.content.map_field:
            class: CMS\Bundle\ContentBundle\Entity\Fields\MapField
            calls:
                - [ setTemplating, [ '@templating' ] ]

    cms.content.weather_field:
                class: CMS\Bundle\ContentBundle\Entity\Fields\WeatherField
                calls:
                    - [ setTemplating, [ '@templating' ] ]

    cms.content.doctrine.entity_listener_resolver:
        class: CMS\Bundle\ContentBundle\Doctrine\EntityListenerResolver
        arguments: [ "@service_container" ]


    cms.content.entity_listener.content:
        class: CMS\Bundle\ContentBundle\Listener\ContentListener
        arguments: [ "@service_container" ]
        tags:
            -  { name: doctrine.entity_listener, event: postLoad }

    cms.content.api.manager:
        class: CMS\Bundle\ContentBundle\Manager\ApiManager

    cms.core.metas.twig_extension:
            class: CMS\Bundle\ContentBundle\Twig\Extension\MetaExtension
            public: false
            arguments: ["@service_container"]
            tags:
                - { name: twig.extension }

    cms.content.content_subscriber:
        class: CMS\Bundle\ContentBundle\Event\ContentSubscriber
        arguments: ["@cms.content.repository.meta"]
        tags:
            - { name: kernel.event_subscriber }

    cms.content.repository.content:
            class: CMS\Bundle\ContentBundle\Entity\Repository\ContentRepository
            factory: ['@doctrine.orm.default_entity_manager', getRepository]
            arguments: ['ContentBundle:Content']

    cms.content.repository.meta:
                class: CMS\Bundle\ContentBundle\Entity\Repository\MetaRepository
                factory: ['@doctrine.orm.default_entity_manager', getRepository]
                arguments: ['ContentBundle:Meta']

    cms.content.query.twig_extension:
        class: CMS\Bundle\ContentBundle\Twig\Extension\QueryExtension
        public: false
        arguments: ["@cms.content.repository.content"]
        tags:
            - { name: twig.extension }