parameters:
    cms_core.form.extension.help.class: 'CMS\Bundle\CoreBundle\Form\Extension\FieldTypeHelpExtension'
    cms_core.file.twig.extension.class: 'CMS\Bundle\CoreBundle\Twig\Extension\FileExtension'
    cms_core.option.twig.extension.class: 'CMS\Bundle\CoreBundle\Twig\Extension\OptionExtension'
    cms_core.boolean.twig.extension.class: 'CMS\Bundle\CoreBundle\Twig\Extension\BooleanIconExtension'
    cms_core.meta_user.twig.extension.class: 'CMS\Bundle\CoreBundle\Twig\Extension\MetaUserExtension'

services:
    cms_core.form.extension.help:
        class: '%cms_core.form.extension.help.class%'
        tags:
            - { name: form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
    cms.core.repository.language:
        class: CMS\Bundle\CoreBundle\Entity\Repository\LanguageRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: ['CoreBundle:Language']

    cms.core.mailer:
        class: CMS\Bundle\CoreBundle\Manager\MailerManager
        arguments: ['@mailer', '@templating', '@doctrine.orm.entity_manager', '@translator']

    cms.core.repository.user_meta:
        class: CMS\Bundle\CoreBundle\Entity\Repository\UserMetaRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: ['CoreBundle:UserMeta']

    cms.core.repository.user:
        class: CMS\Bundle\CoreBundle\Entity\Repository\UserRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: ['CoreBundle:User']

    cms.core.repository.option:
        class: CMS\Bundle\CoreBundle\Entity\Repository\OptionRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: ['CoreBundle:Option']

    cms.core.repository.widget:
        class: CMS\Bundle\CoreBundle\Entity\Repository\WidgetRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: ['CoreBundle:Widget']

    cms.core.factory.widget:
            class: CMS\Bundle\CoreBundle\Classes\WidgetFactory
            arguments: ['@templating', '@doctrine.orm.entity_manager', "@service_container"]

    cms.core.option_manager:
        class: CMS\Bundle\CoreBundle\Manager\OptionManager
        arguments: ['@doctrine.orm.entity_manager', '@cms.core.repository.option']

    cms.core.meta_manager:
        class: CMS\Bundle\CoreBundle\Manager\UserMetaManager
        arguments: ['@doctrine.orm.entity_manager', '@cms.core.repository.user_meta', '@cms.core.repository.user']

    cms.core.theme_manager:
        class: CMS\Bundle\CoreBundle\Manager\ThemeManager

    cms.core.class.general_option:
        class: CMS\Bundle\CoreBundle\Classes\GeneralOptions
        arguments: ['@cms.core.repository.option', '@cms.media.repository.media']

    cms.core.form.type.dropzone:
        class: CMS\Bundle\CoreBundle\Form\Type\DropzoneType
        tags:
            - { name: form.type, alias: dropzone  }

    cms.core.form.type.dropzone_extension:
        class: CMS\Bundle\CoreBundle\Form\Extension\DropzoneTypeExtension
        tags:
            - { name: form.type_extension, alias: dropzone, extended_type: CMS\Bundle\CoreBundle\Form\Type\DropzoneType }

    cms.core.form.type.form_row_extension:
        class: CMS\Bundle\CoreBundle\Form\Extension\FormRowTypeExtension
        tags:
            - { name: form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }


    cms.core.form.type.entity_hidden:
        class: CMS\Bundle\CoreBundle\Form\Type\EntityHiddenType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: entity_hidden }

    cms.core.twig.file.extension:
        class: '%cms_core.file.twig.extension.class%'
        arguments: ['@kernel']
        tags:
            - { name: twig.extension }

    cms.core.twig.booleanicon.extension:
        class: '%cms_core.boolean.twig.extension.class%'
        public: true
        tags:
            - { name: twig.extension }

    cms.core.twig.meta_user.extension:
        class: '%cms_core.meta_user.twig.extension.class%'
        arguments:
          container: "@service_container"
          service: "@security.authorization_checker"
        tags:
         - { name: twig.extension }

    cms.core.twig.option.extension:
            class: '%cms_core.option.twig.extension.class%'
            arguments: ['@cms.core.repository.option']
            tags:
                - { name: twig.extension }

    cms.core.form.type.image:
            class: CMS\Bundle\CoreBundle\Form\Type\ImageType
            arguments: ["@doctrine.orm.entity_manager"]
            tags:
                - { name: form.type, alias: image }

    cms.core.form.type.image_extension:
            class: CMS\Bundle\CoreBundle\Form\Extension\ImageTypeExtension
            tags:
                - { name: form.type_extension, alias: image, extended_type: CMS\Bundle\CoreBundle\Form\Type\ImageType }

    cms.core.form.type.general_options:
            class: CMS\Bundle\CoreBundle\Form\GeneralOptionsType
            arguments: ["@doctrine.orm.entity_manager"]
            tags:
                - { name: form.type }

    cms.core.instagram.twig_extension:
            class: CMS\Bundle\CoreBundle\Twig\Extension\InstagramExtension
            public: false
            arguments: ["@service_container"]
            tags:
                - { name: twig.extension }

    cms.core.social.twig_extension:
        class: CMS\Bundle\CoreBundle\Twig\Extension\SocialExtension
        public: false
        arguments: ["@request_stack"]
        calls:
            - [ setTemplating, [ '@twig' ] ]
        tags:
            - { name: twig.extension }

    cms.core.gmdate.twig_extension:
        class: CMS\Bundle\CoreBundle\Twig\Extension\GMDateExtension
        public: true
        tags:
            - { name: twig.extension }

    cms.core.widget.twig_extension:
        class: CMS\Bundle\CoreBundle\Twig\Extension\WidgetExtension
        public: true
        arguments: ["@cms.core.repository.widget", "@service_container"]
        tags:
            - { name: twig.extension }