<?php

namespace CMS\Bundle\MenuBundle\Entity\Repository;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends NestedTreeRepository
{

	public function findAll()
	{
		return $this->_em
			        ->createQueryBuilder('e')
			        ->select('e')
			        ->from('MenuBundle:Entry', 'e')
			        ->where('e.lvl > 0')
			        ->orderby('e.lft', 'asc')
			        ->getQuery()
			        ->getResult();
	}

	public function getSiblings($entity)
	{
		if ( is_null($entity) ) {
			return $this->_em
			        ->createQueryBuilder('e')
			        ->select('e')
			        ->from('MenuBundle:Entry', 'e')
			        ->where('e.lvl > 0');
		}

		return $this->_em
					->createQueryBuilder('e')
					->select('e')
					->from('MenuBundle:Entry', 'e')
					->where('e.id != :id')
					->setParameter('id', $entity->getId())
					->andWhere('e.lvl = :lvl')
					->setParameter('lvl', $entity->getLvl());
	}
}
