<?php

namespace CMS\Bundle\ContactBundle\Repository;

/**
 * ContactFormsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactFormsRepository extends \Doctrine\ORM\EntityRepository
{
}
